
search_tweets_api:
    bearer_token: AAAAAAAAAAAAAAAAAAAAAADOOQEAAAAAA48TXRx7xRlgojG3H2jWqwo5Hx8%3DaTenugiMmFNjlhX1nS8a1wxoPkg22bAWwHaYHrFQ07mJcoITQQ
    config:
        tracker_name: Academic Reserach
        max_results: 500
        max_requests: 300
        max_query_len: 1024

mysql_conn:
    user: root
    password: k4Rl4#05
    host: localhost
    #database: mydissertation
    
mysql_conn_hostgator:
    user: tanniest_karla
    password: ezgTcfQLAf7aBjGK
    host: mx74.hostgator.mx
    database: tanniest_sentimentanalysis
